### ISSUE TITLE
failed to get working from repo, however did find out something else

### ISSUE THREAD

**Issue by rclarke2050** [zaccharles/lambda-native#6]
apparrently, using CoreRT doesnt really work in real world scenarios.

However, i found a new article mentioning ReadyToRun images, which could prove to be a winner.
https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-6/
https://aws.amazon.com/blogs/developer/announcing-amazon-lambda-runtimesupport/

if you could include an example using this idea, that would be awesome!!! ;-)

Thanks alot for at least your hard work here, but it seems like it might be redundant now R2R is coming....

**Comment by zaccharles** [comment]
Hey @rclarke2050, I think you're right on all accounts. CoreRT in the real world is difficult to use and hard to please. Now that ReadyToRun can be used, that's worth further investigation. I think it would need to be used in conjunction with self contained apps (since custom Lambda runtimes don't have a .NET runtime installed) and IL-trimming (to bring the size back down a bit). If all of those play nicely together, it's probably a winning combination.

You also mentioned Amazon's Lambda RuntimeSupport library which was released after Lambda Native. It's worth noting that they do basically exactly the same thing, with a slightly different interface.  Given people are paid to maintain RuntimeSupport, that's probably a better option than Lambda Native.

I might try to find some time to try the above :)

**Comment by rclarke2050** [comment]
Hi Zac,
Thanks for the quick reply.  I managed to get your article working by the end of today, however had to go about it in a different way from running in Windows.

I'll try to share the file tomorrow.  however, dont get me wrong, I am happy to read your article, and get to understand what you've done. I think its cool!  and what we're all trying to do is get this damn cold-start down to 1ms ;-)

**Comment by rclarke2050** [comment]
heres what my docker-build looks like:


![docker-build cmd](https://user-images.githubusercontent.com/53872564/64618357-03b37500-d3d8-11e9-9a53-14ca565faf61.png)
Sure i use d:\ to get the file back, but in a CI/CD environment, you can change that to what ever you want.

On windows, i decided to do the build inside a docker container, so followed your article to some degree, and created a dockerfile for the build, this work quite ok.
![dockerfile jpg](https://user-images.githubusercontent.com/53872564/64618369-0910bf80-d3d8-11e9-9e4a-5826d83981be.png)

The only issue i have at the moment, is trying to get this to work in the following Handler definition:

public class Handler : IHandler<APIGatewayProxyRequest, APIGatewayProxyResponse>
or 
public class Handler : IAsyncHandler<APIGatewayProxyRequest, APIGatewayProxyResponse>

cant seem to get this to work properly, always comes back with a segment error.  strange.

;-)

**Comment by ifew** [comment]
> apparrently, using CoreRT doesnt really work in real world scenarios.
> 
> However, i found a new article mentioning ReadyToRun images, which could prove to be a winner.
> https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-6/
> https://aws.amazon.com/blogs/developer/announcing-amazon-lambda-runtimesupport/
> 
> if you could include an example using this idea, that would be awesome!!! ;-)
> 
> Thanks alot for at least your hard work here, but it seems like it might be redundant now R2R is coming....

I implement to change from CoreRT to using .NET Core 3.0.100 ReadyToRun feature and it's Work!
please check out here https://github.com/ifew/aws-lambda-lambdanative-db
